### ISSUE TITLE
Reorganize excellent-128.c

### ISSUE THREAD

**Issue by nanis** [briandfoy/excellent_numbers#11]
- [x] Add `getopt` style command line argument support for:
  - number of digits
  - start value for `a`
  - end value for `a`
  - report frequency (`SIGALRM`): minutes between reports
  - signal check frequency: seconds between signal checks
  - command line help
- [x] Replace `stop_a[]` with formula (eb93b137)
- [x] Dynamically adjust number of iterations per second based on current performance
- [x] Improve calculation of `b` in `check_excellent`: No division inside `sqrt`.
- [x] Print nice time stamps ( see #5 ) (60e06dc7 and 75112687)
- [x] Clean up `Makefile` (b1f2e3b92, d4b5b9fb, and b1f2e3b9)

**Comment by briandfoy** [comment]
If all are these are done, can we close this issue?

**Comment by nanis** [comment]
They are done, but I haven't merged them to master because the new excellent-128.c is drastically different. I want you try it first, and, if it is OK with you, we can merge and close.
