### ISSUE TITLE
Implement solution from HN

### ISSUE THREAD

**Issue by nanis** [briandfoy/excellent_numbers#12]
See [comment by `Someone`](https://news.ycombinator.com/item?id=10915461) on [HN thread](https://news.ycombinator.com/item?id=10909909), and 53da284a.

So, the problem turns into a one-time factorization operation.

**Comment by briandfoy** [comment]
The solution from Hacker News is flawed, but Matthew Arcus got it right: https://matthewarcus.wordpress.com/2016/01/16/excellent-numbers/ .

I've added it as python/excellent-squares.py in b49212b
