### ISSUE TITLE
Obtain factors using repunits

### ISSUE THREAD

**Issue by nanis** [briandfoy/excellent_numbers#13]
See http://stdkmd.com/nrr/repunit/ for lists, and https://en.wikipedia.org/wiki/Repunit for explanation.

For example, (10<sup>42</sup> - 1)/9 = 3 × 72 × 11 × 13 × 37 × 43 × 127 × 239 × 1933 × 2689 × 4649 × 459691 × 909091 × 10838689. Therefore, 10<sup>42</sup> - 1 = 3<sup>3</sup> × 7<sup>2</sup> × 11 × 13 × 37 × 43 × 127 × 239 × 1933 × 2689 × 4649 × 459691 × 909091 × 10838689.

**Comment by briandfoy** [comment]
Maybe this should be a new Perl module, but then maybe not. I think a JSON version of those resources would be nice.

The next part of the problem is the repunit factors for higher values of n than someone has computed.
